### ISSUE TITLE
Give additional debug information in the logs when "Load Error FAILED"

### ISSUE THREAD

**Issue by v1bh0r** [specmatic/specmatic#553]
**Is your feature request related to a problem? Please describe.**
It is frustrating to debug errors reported by "specmatic test" when "Load Error FAILED".

**Describe the solution you'd like**
Given that there's an issue found during the validation of the api-spec, indicate the line number where the problem was encountered in.

**Describe alternatives you've considered**
Validate using swagger-cli
Resolve all the errors and warnings reported by Spotlight studio

**Additional context**
Here's a sample error reported in 0.54.0
```
mediaType.schema must not be null
Load Error FAILED
Reason: mediaType.schema must not be null



Unsuccessful Scenarios:
  "Load Error FAILED"
        Reason: mediaType.schema must not be null

Tests run: 1, Successes: 0, Failures: 1, Errors: 0
```

**Comment by joelrosario** [comment]
Hi @v1bh0r , yes that doesn't seem like a helpful error message.

It would help us if you could share the contract that you used when you got this message.

Thanks.

**Comment by v1bh0r** [comment]
@joelrosario, Sorry for the delay.

Here's an example:

```yaml
openapi: 3.0.1
info:
  title: Contract for the petstore service
  version: '1'
paths:
  '/pets/{petid}':
    get:
      summary: Should be able to get a pet by petId
      parameters:
        - name: petid
          in: path
          required: true
          schema:
            type: number
          examples:
            200_OKAY:
              value: 1
      responses:
        '200':
          description: Should be able to get a pet by petId
          content:
            application/json:
              schema:
                required:
                  - id
                  - name
                  - status
                  - type
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  type:
                    type: string
                  status:
                    type: string
              examples:
                200_OKAY:
                  value: '{any}'
        '400':
          $ref: '#/components/responses/400'
components:
  responses:
    '400':
      content:
        application/json:
          examples:
            '400':
              value:
                errors:
                  category: API_ERROR
                  code: MISSING_REQUIRED_PARAMETER
                  detail: Missing required parameter
      description: ''
```

Here's what I observed:
```
➜  ~ specmatic test ~/Downloads/specmatic-issue/service.yaml --testBaseURL=https://my-json-server.typicode.com/znsio/specmatic-documentation

mediaType.schema must not be null
Load Error FAILED
Reason: mediaType.schema must not be null



Unsuccessful Scenarios:
  "Load Error FAILED"
        Reason: mediaType.schema must not be null

Tests run: 1, Successes: 0, Failures: 1, Errors: 0
➜  ~ swagger-cli validate ~/Downloads/specmatic-issue/service.yaml
/Users/vibhor/Downloads/specmatic-issue/service.yaml is valid
```

The error goes away if I add the schema:

```yaml
openapi: 3.0.1
info:
  title: Contract for the petstore service
  version: '1'
paths:
  '/pets/{petid}':
    get:
      summary: Should be able to get a pet by petId
      parameters:
        - name: petid
          in: path
          required: true
          schema:
            type: number
          examples:
            200_OKAY:
              value: 1
      responses:
        '200':
          description: Should be able to get a pet by petId
          content:
            application/json:
              schema:
                required:
                  - id
                  - name
                  - status
                  - type
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  type:
                    type: string
                  status:
                    type: string
              examples:
                200_OKAY:
                  value: '{any}'
        '400':
          $ref: '#/components/responses/400'
components:
  responses:
    '400':
      content:
        application/json:
          examples:
            '400':
              value:
                errors:
                  category: API_ERROR
                  code: MISSING_REQUIRED_PARAMETER
                  detail: Missing required parameter
          schema:
            type: object
            properties:
              errors:
                type: object
                properties:
                  category:
                    type: string
                  code:
                    type: string
                  detail:
                    type: string
            x-examples:
              example-1:
                errors:
                  category: API_ERROR
                  code: MISSING_REQUIRED_PARAMETER
                  detail: Missing required parameter
      description: ''
```

**Comment by sergeyklay** [comment]
Btw, I spent many hours before I realized that specmatic does not support this

```diff
#
# Some code, omitted for brevity
#
                    template:
                      type: object
                      properties:
                        name:
                          type: string
                        params:
                          type: object
+                         # This leads to fail contract tests
+                         additionalProperties: {}
+                         minProperties: 1
                          properties:
                            foo:
                              type: string
                              example: "bar"
```


And error message was:
```
% specmatic test --debug --testBaseURL="http://127.0.0.1:8197"
No contractPaths specified. Using configuration file named ./specmatic.json
Loading config file ./specmatic.json
Using contracts in home dir
Contract file paths in ./specmatic.json:
  /Users/egrep/.specmatic/repos/swagger-docs/contracts/v1/email-templates/email-templates.semver.addons.send/contract.spec
Parsing contract file /Users/egrep/.specmatic/repos/swagger-docs/contracts/v1/email-templates/email-templates.semver.addons.send/contract.spec, absolute path /Users/egrep/.specmatic/repos/swagger-docs/contracts/v1/email-templates/email-templates.semver.addons.send/contract.spec
valueSchema.types must not be null
java.lang.NullPointerException: valueSchema.types must not be null
	at in.specmatic.conversions.OpenApiSpecification.toDictionaryPattern(OpenApiSpecification.kt:784)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern(OpenApiSpecification.kt:598)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern$default(OpenApiSpecification.kt:539)
	at in.specmatic.conversions.OpenApiSpecification.toSchemaProperties(OpenApiSpecification.kt:821)
	at in.specmatic.conversions.OpenApiSpecification.toJsonObjectPattern(OpenApiSpecification.kt:802)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern(OpenApiSpecification.kt:563)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern$default(OpenApiSpecification.kt:539)
	at in.specmatic.conversions.OpenApiSpecification.toSchemaProperties(OpenApiSpecification.kt:821)
	at in.specmatic.conversions.OpenApiSpecification.toJsonObjectPattern(OpenApiSpecification.kt:802)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern(OpenApiSpecification.kt:563)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern$default(OpenApiSpecification.kt:539)
	at in.specmatic.conversions.OpenApiSpecification.toSchemaProperties(OpenApiSpecification.kt:821)
	at in.specmatic.conversions.OpenApiSpecification.toJsonObjectPattern(OpenApiSpecification.kt:802)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern(OpenApiSpecification.kt:563)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern$default(OpenApiSpecification.kt:539)
	at in.specmatic.conversions.OpenApiSpecification.toSchemaProperties(OpenApiSpecification.kt:821)
	at in.specmatic.conversions.OpenApiSpecification.toJsonObjectPattern(OpenApiSpecification.kt:802)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern(OpenApiSpecification.kt:563)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern$default(OpenApiSpecification.kt:539)
	at in.specmatic.conversions.OpenApiSpecification.toSchemaProperties(OpenApiSpecification.kt:821)
	at in.specmatic.conversions.OpenApiSpecification.toJsonObjectPattern(OpenApiSpecification.kt:802)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern(OpenApiSpecification.kt:563)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern$default(OpenApiSpecification.kt:539)
	at in.specmatic.conversions.OpenApiSpecification.resolveReference(OpenApiSpecification.kt:848)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern(OpenApiSpecification.kt:613)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern$default(OpenApiSpecification.kt:539)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern(OpenApiSpecification.kt:537)
	at in.specmatic.conversions.OpenApiSpecification.toSpecmaticPattern$default(OpenApiSpecification.kt:536)
	at in.specmatic.conversions.OpenApiSpecification.toHttpRequestPatterns(OpenApiSpecification.kt:473)
	at in.specmatic.conversions.OpenApiSpecification.toScenarioInfosWithExamples(OpenApiSpecification.kt:261)
	at in.specmatic.conversions.OpenApiSpecification.toScenarioInfos(OpenApiSpecification.kt:102)
	at in.specmatic.core.FeatureKt.scenarioInfos(Feature.kt:1669)
	at in.specmatic.core.FeatureKt.lex(Feature.kt:1632)
	at in.specmatic.core.FeatureKt.lex(Feature.kt:1629)
	at in.specmatic.core.FeatureKt.parseGherkinStringToFeature(Feature.kt:66)
	at in.specmatic.core.FeatureKt.parseContractFileToFeature(Feature.kt:59)
	at in.specmatic.core.FeatureKt.parseContractFileToFeature(Feature.kt:45)
	at in.specmatic.core.FeatureKt.parseContractFileToFeature$default(Feature.kt:44)
	at in.specmatic.test.SpecmaticJUnitSupport.loadTestScenarios(SpecmaticJUnitSupport.kt:145)
	at in.specmatic.test.SpecmaticJUnitSupport.contractTest(SpecmaticJUnitSupport.kt:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestFactoryMethod(TimeoutExtension.java:102)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.lambda$invokeTestMethod$1(TestFactoryTestDescriptor.java:97)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.invokeTestMethod(TestFactoryTestDescriptor.java:95)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at application.TestCommand.call(TestCommand.kt:210)
	at application.TestCommand.call(TestCommand.kt:45)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at application.QontractApplicationRunner.run(QontractApplicationRunner.kt:16)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at application.SpecmaticApplication$Companion.main(SpecmaticApplication.kt:29)
	at application.SpecmaticApplication.main(SpecmaticApplication.kt)

Load Error FAILED
Reason: valueSchema.types must not be null



Unsuccessful Scenarios:
  "Load Error FAILED"
        Reason: valueSchema.types must not be null
```


Frankly speaking, message "Reason: valueSchema.types must not be null" says nothing.

**Comment by harikrishnan83** [comment]
@sergeyklay Thanks for adding to this thread. Agree, the error message is not helpful at. We are taking a look into this.

**Comment by joelrosario** [comment]
Hi @v1bh0r, thanks for pointing this out. We've added validations this and a few more such cases, as you can see from the PR on this timeline. It'll be out soon with the next release.
