### ISSUE TITLE
Regression changes for handling parameter length in 0.60.0 and 0.61.0

### ISSUE THREAD

**Issue by sergeyklay** [specmatic/specmatic#607]
**Description**
When specifying the minimum and maximum length of a parameter, its pattern is not taken into account.

Suppose we have defined the following path (say, foo-api.yaml):
```yaml

# ...

  /v1/foo/{id}:
    delete:
      summary: Delete 'foo'
      operationId: foo.delete
      tags: [ foo ]
      parameters:
        - in: path
          name: id
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-000030[aA]{2}$'
            # the regex above limits the length;
            # however, some tools might require explicit settings:
            minLength: 27
            maxLength: 27
          example: CAC10D70-0000-0000-000030AA
          required: true
          description: ID of the requested 'foo'
      responses:
        '204':
          description: Successful operation

# ...

```

and the following contract test (say, specmatic-pattern-issue.spec):
```Gherkin
Feature: Foo API

  Background:
    Given openapi ./foo-api.yaml

  Scenario Outline: Delete foo
    When DELETE /v1/foo/(id:string)
    Then status 204
    Examples:
      | id                          |
      | CAC10D70-0000-0000-000030AA |
```

Launching specmatic results in the following error:
```
$ java -jar specmatic.jar test contracts/specmatic-pattern-issue.spec --testBaseURL=http://127.0.0.1:5000 --debug

Parsing contract file contracts/specmatic-pattern-issue.spec, absolute path /home/runner/work/specmatic-testing-example/specmatic-testing-example/contracts/specmatic-pattern-issue.spec
Scenario: "Delete foo" PATH: "/v1/foo/MNLIY" is not as per included wsdl / OpenApi spec
ContractException(errorMessage=Scenario: "Delete foo" PATH: "/v1/foo/MNLIY" is not as per included wsdl / OpenApi spec, breadCrumb=, exceptionCause=null, scenario=null)
	at in.specmatic.conversions.OpenApiSpecification.matches(OpenApiSpecification.kt:114)
	at in.specmatic.core.FeatureKt.lexScenario(Feature.kt:1440)
	at in.specmatic.core.FeatureKt.scenarioInfos(Feature.kt:1705)
	at in.specmatic.core.FeatureKt.lex(Feature.kt:1647)
	at in.specmatic.core.FeatureKt.lex(Feature.kt:1644)
	at in.specmatic.core.FeatureKt.parseGherkinStringToFeature(Feature.kt:66)
	at in.specmatic.core.FeatureKt.parseContractFileToFeature(Feature.kt:59)
	at in.specmatic.core.FeatureKt.parseContractFileToFeature(Feature.kt:45)
	at in.specmatic.core.FeatureKt.parseContractFileToFeature$default(Feature.kt:44)
	at in.specmatic.test.SpecmaticJUnitSupport.loadTestScenarios(SpecmaticJUnitSupport.kt:150)
	at in.specmatic.test.SpecmaticJUnitSupport.contractTest(SpecmaticJUnitSupport.kt:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestFactoryMethod(TimeoutExtension.java:102)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.lambda$invokeTestMethod$1(TestFactoryTestDescriptor.java:97)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestFactoryTestDescriptor.invokeTestMethod(TestFactoryTestDescriptor.java:95)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at application.SpecmaticApplication$Companion.main(SpecmaticApplication.kt:29)
	at application.SpecmaticApplication.main(SpecmaticApplication.kt)

Load Error FAILED
Reason: Scenario: "Delete foo" PATH: "/v1/foo/MNLIY" is not as per included wsdl / OpenApi spec



Unsuccessful Scenarios:
  "Load Error FAILED"
        Reason: Scenario: "Delete foo" PATH: "/v1/foo/MNLIY" is not as per included wsdl / OpenApi spec

Tests run: 1, Successes: 0, Failures: 1, Errors: 0
```

after removing parameter length as follows
```diff

# ...

  /v1/foo/{id}:
    delete:
      summary: Delete 'foo'
      operationId: foo.delete
      tags: [ foo ]
      parameters:
        - in: path
          name: id
          schema:
            type: string
            pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-000030[aA]{2}$'
-           # the regex above limits the length;
-           # however, some tools might require explicit settings:
-           minLength: 27
-           maxLength: 27
          example: CAC10D70-0000-0000-000030AA
          required: true
          description: ID of the requested 'foo'
      responses:
        '204':
          description: Successful operation

# ...

```

everything is going well and the tests are passing.

**Expected behavior**

Some tools need an explicit parameter length, so I would prefer to use `minLength` and `maxLength`.

I created a reproducible example: https://github.com/sergeyklay/specmatic-testing-example/pull/17

And as you can see, the previous version of specmatic is not affected by this problem.
- **0.59.0:** **OK** https://github.com/sergeyklay/specmatic-testing-example/actions/runs/4171791072/jobs/7222114358
- **0.60.0:** **FAILED** https://github.com/sergeyklay/specmatic-testing-example/actions/runs/4171791072/jobs/7222114489
- **0.61.0:** **FAILED** https://github.com/sergeyklay/specmatic-testing-example/actions/runs/4171791072/jobs/7222114654

**Screenshots**
-

**System Information:**
 - OS & version: -
 - Browser & version: -
 - Specmatic version: 0.60.0 and 0.61.0
 - Java version: 1.8.0_361

**Comment by sergeyklay** [comment]
I found a commit that causes the issue described above with the help of git bisect. It is: 1a73c8e5e9576b327a329f2db05a068238f6fc25

**Comment by joelrosario** [comment]
Hi @sergeyklay , thanks for the bug report, and the detailed steps for reproducing, including the test. We will be merging your PR shortly. It also requires a couple of further changes, which we will do as well on top of it.
