### ISSUE TITLE
[SOAP] Can't recognize child node xs:attribute

### ISSUE THREAD

**Issue by aeoncl** [specmatic/specmatic#670]
**Description**
Hi, we have in our soap definition an abstract model which is a complex type that has a xs:attribute type directly as children.
Specmatic doesn't support this

**Steps to reproduce**
1. Run the following command using the provided [wsdl & xsd](https://github.com/znsio/specmatic/files/11833478/myservice.zip): 
`specmatic import myservice.wsdl`
2. The following error message will pop up: 
```kotlin
Error getting types for WSDL type "tns:my-request", <xs:element name="my-request">: Couldn't recognize child node <xs:attribute name="application-id" type="xs:string"><xs:annotation><xs:documentation>This is optional as a given ID will be given by the
                                                application</xs:documentation></xs:annotation></xs:attribute>
ContractException(errorMessage=Couldn't recognize child node <xs:attribute name="application-id" type="xs:string"><xs:annotation><xs:documentation>This is optional as a given ID will be given by the
                                                application</xs:documentation></xs:annotation></xs:attribute>, breadCrumb=, exceptionCause=null, scenario=null, isCycle=false)
        at in.specmatic.core.wsdl.parser.message.ComplexElementKt.complexTypeChildNode(ComplexElement.kt:96)
        at in.specmatic.core.wsdl.parser.message.ComplexElementKt.generateChildren(ComplexElement.kt:81)
        at in.specmatic.core.wsdl.parser.message.ComplexTypeExtension.process(ComplexTypeExtension.kt:21)
        at in.specmatic.core.wsdl.parser.message.ComplexElementKt.generateChildren(ComplexElement.kt:83)
        at in.specmatic.core.wsdl.parser.message.ComplexType.generateChildren(ComplexElement.kt:75)
        at in.specmatic.core.wsdl.parser.message.ComplexElement.deriveSpecmaticTypes(ComplexElement.kt:23)
        at in.specmatic.core.wsdl.parser.message.ReferredType.deriveSpecmaticTypes(ReferredType.kt:33)
        at in.specmatic.core.wsdl.parser.message.ParseMessageWithElementRef.execute(ParseMessageWithElementRef.kt:18)
        at in.specmatic.core.wsdl.parser.SOAP11Parser.parsePayloadTypes(SOAP11Parser.kt:77)
        at in.specmatic.core.wsdl.parser.SOAP11Parser.parseOperation(SOAP11Parser.kt:38)
        at in.specmatic.core.wsdl.parser.SOAP11Parser.convertToGherkin(SOAP11Parser.kt:18)
        at in.specmatic.core.wsdl.parser.WSDL.convertToGherkin(WSDL.kt:212)
        at application.ImportCommandKt.convertWSDL(ImportCommand.kt:94)
        at application.ImportCommand$call$1.invoke(ImportCommand.kt:44)
        at application.ImportCommand$call$1.invoke(ImportCommand.kt:37)
        at in.specmatic.core.log.LoggingKt.logException(Logging.kt:11)
        at application.ImportCommand.call(ImportCommand.kt:37)
        at application.ImportCommand.call(ImportCommand.kt:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at application.QontractApplicationRunner.run(QontractApplicationRunner.kt:16)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at application.SpecmaticApplication$Companion.main(SpecmaticApplication.kt:29)
        at application.SpecmaticApplication.main(SpecmaticApplication.kt)

Couldn't recognize child node <xs:attribute name="application-id" type="xs:string"><xs:annotation><xs:documentation>This is optional as a given ID will be given by the
                                                application</xs:documentation></xs:annotation></xs:attribute>
ContractException(errorMessage=Couldn't recognize child node <xs:attribute name="application-id" type="xs:string"><xs:annotation><xs:documentation>This is optional as a given ID will be given by the
                                                application</xs:documentation></xs:annotation></xs:attribute>, breadCrumb=, exceptionCause=null, scenario=null, isCycle=false)
        at in.specmatic.core.wsdl.parser.message.ComplexElementKt.complexTypeChildNode(ComplexElement.kt:96)
        at in.specmatic.core.wsdl.parser.message.ComplexElementKt.generateChildren(ComplexElement.kt:81)
        at in.specmatic.core.wsdl.parser.message.ComplexTypeExtension.process(ComplexTypeExtension.kt:21)
        at in.specmatic.core.wsdl.parser.message.ComplexElementKt.generateChildren(ComplexElement.kt:83)
        at in.specmatic.core.wsdl.parser.message.ComplexType.generateChildren(ComplexElement.kt:75)
        at in.specmatic.core.wsdl.parser.message.ComplexElement.deriveSpecmaticTypes(ComplexElement.kt:23)
        at in.specmatic.core.wsdl.parser.message.ReferredType.deriveSpecmaticTypes(ReferredType.kt:33)
        at in.specmatic.core.wsdl.parser.message.ParseMessageWithElementRef.execute(ParseMessageWithElementRef.kt:18)
        at in.specmatic.core.wsdl.parser.SOAP11Parser.parsePayloadTypes(SOAP11Parser.kt:77)
        at in.specmatic.core.wsdl.parser.SOAP11Parser.parseOperation(SOAP11Parser.kt:38)
        at in.specmatic.core.wsdl.parser.SOAP11Parser.convertToGherkin(SOAP11Parser.kt:18)
        at in.specmatic.core.wsdl.parser.WSDL.convertToGherkin(WSDL.kt:212)
        at application.ImportCommandKt.convertWSDL(ImportCommand.kt:94)
        at application.ImportCommand$call$1.invoke(ImportCommand.kt:44)
        at application.ImportCommand$call$1.invoke(ImportCommand.kt:37)
        at in.specmatic.core.log.LoggingKt.logException(Logging.kt:11)
        at application.ImportCommand.call(ImportCommand.kt:37)
        at application.ImportCommand.call(ImportCommand.kt:20)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at application.QontractApplicationRunner.run(QontractApplicationRunner.kt:16)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at application.SpecmaticApplication$Companion.main(SpecmaticApplication.kt:29)
        at application.SpecmaticApplication.main(SpecmaticApplication.kt)
```

**Expected behavior**
I expected the wsdl to be read correctly and getting a .spec file

**Screenshots**

**System Information:**
 - OS & version Windows 11 Build 21H2
 - Browser & version: Firefox 102
 - Specmatic version: 0.70.1
 - JDK version: 17

**Additional context**
The issues is caused by the fact that we have no ComplexContent element inside the ComplexType.
Specmatics parser doesn't expect to have a xs:attribute directly as a child of a ComplexType
(ComplexElement.kt => line 90)

WSDLs can come in many forms, it can be hard to reimplement a parser from scratch like it was done in Specmatic. Maybe a library can do the parsing??

Thank you for your work :)

**Comment by jaydeepk** [comment]
Thanks for reporting this @aeoncl.
We will have a look at this and get back to you.
