### ISSUE TITLE
NoSuchMethodError with springboot 2, maven 3, java17

### ISSUE THREAD

**Issue by kiranpatel11** [specmatic/specmatic#692]
**Description**
I am getting below exception when using the maven dependencies in the springboot project with Java 17.

```
java.lang.NoSuchMethodError: 'java.lang.Comparable kotlin.collections.CollectionsKt.maxOrThrow(java.lang.Iterable)'
        at in.specmatic.test.APICoverageReport.toLogString(SpecmaticJUnitSupport.kt:60)
        at in.specmatic.test.TestReport.printReport(SpecmaticJUnitSupport.kt:149)
        at in.specmatic.test.SpecmaticJUnitSupport$Companion.report(SpecmaticJUnitSupport.kt:178)
        at in.specmatic.test.SpecmaticJUnitSupport.report(SpecmaticJUnitSupport.kt)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```

**Steps to reproduce**
1. Create springboot project with specmatic dependencies 
2. Run specmatic contract tests using mvn failsafe plugin

**System Information:**
- Java 17
- Junit5
- Maven 3.6.3
- Springboot 2.7.14
- Specmatic 0.73.0

**Additional context**
- Also tried with specmatic 0.72.0
- Without the specmatic related changes the application build works as expected.
- Specmatic tests are getting executed as expected.

**Comment by jaydeepk** [comment]
Hi @kiranpatel11 
Thanks for reporting this issue.
We have come across this issue earlier and it is related to SpringBoot (#530)
SpringBoot tries to bring its own version of Kotlin into the project which causes a conflict.
We can resolve this conflict my explicitly mentioning the version of kotlin that you need.
Please add the following lines inside the properties section of your pom.xml:
```xml
<kotlin-coroutines.version>1.6.4</kotlin-coroutines.version>
<kotlin.version>1.7.20</kotlin.version>
```
